# Generated by Django 2.2.3 on 2020-08-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
