# Generated by Django 2.2.3 on 2020-08-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contatos_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/'),
        ),
    ]
